services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: airtable-dashboard

  backend:
    build: { context: ./backend, dockerfile: Dockerfile }
    restart: unless-stopped
    ports:
      - "3005:3000"
    depends_on: [mongo, redis]
    env_file: ./backend/.env
    environment:
      MONGODB_URI: mongodb://mongo:27017/airtable-dashboard
      REDIS_URL: redis://redis:6379 # add this line

  frontend:
    build: { context: ./frontend, dockerfile: Dockerfile }
    restart: unless-stopped
    ports:
      - "4200:80"
    depends_on: [backend]

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
